-- 创建数据库

/*
CREATE DATABASE FOO;
*/

USE FOO;

--  3.3.2.1 定义基本表

/*
CREATE TABLE STUDENT (
	SNO   CHAR(9)  PRIMARY KEY,
	SNAME CHAR(20) UNIQUE,
	SSEX  CHAR(2),
	SAGE  SMALLINT,
	SDEPT CHAR(20)
);
*/
/*
CREATE TABLE COURSE (
	CNO     CHAR(4) PRIMARY KEY,
	CNAME   CHAR(40),
	CPNO    CHAR(4) ,
	CCREDIT SMALLINT,
	FOREIGN KEY (CPNO) REFERENCES COURSE(CNO)
);
*/
/*
CREATE TABLE SC (
	SNO   CHAR(9),
	CNO   CHAR(4),
	GRADE SMALLINT,
	PRIMARY KEY (SNO, CNO),
	FOREIGN KEY (SNO) REFERENCES STUDENT(SNO),
	FOREIGN KEY (CNO) REFERENCES COURSE(CNO)
);
*/

-- 3.3.2.4 修改基本表

/*
ALTER TABLE STUDENT ADD S_ENTRANCE DATE;

ALTER TABLE STUDENT ALTER COLUMN SAGE INT;

ALTER TABLE COURSE ADD UNIQUE(CNAME);
*/

-- 3.3.2.5 删除基本表

/*
CREATE TABLE FOO (
	SNO   CHAR(9)  PRIMARY KEY,
	SNAME CHAR(20) UNIQUE,
	SSEX  CHAR(2),
	SAGE  SMALLINT,
	SDEPT CHAR(20)
);
DROP TABLE FOO;
*/

-- 3.3.3.1 建立索引

/*
CREATE UNIQUE INDEX STUSNO ON STUDENT(SNO);
CREATE UNIQUE INDEX COUCNO ON COURSE(CNO);
CREATE UNIQUE INDEX SCNO ON SC(SNO ASC, CNO DESC);
*/

-- 3.3.3.2 删除索引

/*
CREATE UNIQUE INDEX FOO_INDEX ON STUDENT(SNO);
DROP INDEX FOO_INDEX ON STUDENT;
*/


-- 3.4.1.1 选择表中若干列

/*
SELECT SNO, SNAME FROM STUDENT;
SELECT SNAME, SNO, SDEPT FROM STUDENT;
*/

/*
SELECT * FROM STUDENT;
*/

/*
SELECT SNAME, 2004 - SAGE FROM STUDENT;
SELECT SNAME, 'Year of Birth:', 2019 - SAGE, LOWER(SDEPT) FROM STUDENT;
SELECT SNAME NAME, 'Year of Birth:' BIRTH, 2019 - SAGE BIRTHDAY, LOWER(SDEPT) DEPARTMENT FROM STUDENT;
*/

-- 3.4.1.2 选择表中若干元祖

/*
SELECT SNO FROM SC;
SELECT DISTINCT SNO FROM SC;
SELECT ALL SNO FROM SC;
*/

/*
SELECT SNAME FROM STUDENT WHERE SDEPT='CS';
SELECT SNAME, SAGE FROM STUDENT WHERE SAGE < 20;
SELECT DISTINCT SNO FROM SC WHERE GRADE < 60;
*/

/*
SELECT SNAME, SDEPT, SAGE FROM STUDENT WHERE SAGE BETWEEN 20 AND 23;
SELECT SNAME, SDEPT, SAGE FROM STUDENT WHERE SAGE NOT BETWEEN 20 AND 23;
*/

/*
SELECT SNAME, SSEX FROM STUDENT WHERE SDEPT IN ('CS', 'MA', 'IS');
SELECT SNAME, SSEX FROM STUDENT WHERE SDEPT NOT IN ('CS', 'MA', 'IS');
*/

/*
SELECT * FROM STUDENT WHERE SNO LIKE '200215121';
SELECT SNAME, SNO, SSEX FROM STUDENT WHERE SNAME LIKE '刘%';
SELECT SNAME, SNO, SSEX FROM STUDENT WHERE SNAME LIKE '刘____';
SELECT SNAME, SNO, SSEX FROM STUDENT WHERE SNAME LIKE '刘__';
SELECT SNAME, SNO, SSEX FROM STUDENT WHERE SNAME NOT LIKE '刘%';
*/

/*
SELECT CNO, CCREDIT FROM COURSE WHERE CNAME LIKE 'DB\_Design' ESCAPE '\';
*/

/*
SELECT SNO, CNO FROM SC WHERE GRADE IS NULL;
SELECT SNO, CNO FROM SC WHERE GRADE IS NOT NULL;
*/

/*
SELECT SNAME FROM STUDENT WHERE SDEPT='CS' AND SAGE < 20;
SELECT SNAME, SSEX FROM STUDENT WHERE SDEPT='CS' OR SDEPT='MA' OR SDEPT='IS';
*/

-- 3.4.1.3 ORDER BY 子句

/*
SELECT SNO, GRADE FROM SC WHERE CNO='3' ORDER BY GRADE DESC;
SELECT * FROM STUDENT ORDER BY SDEPT, SAGE DESC;
SELECT * FROM STUDENT ORDER BY SDEPT ASC, SAGE DESC;
SELECT * FROM STUDENT ORDER BY SDEPT DESC, SAGE ASC;
*/

-- 3.4.1.4 聚集函数

/*
SELECT COUNT(*) FROM STUDENT;
SELECT COUNT(DISTINCT SNO) FROM SC;
SELECT AVG(GRADE) FROM SC WHERE CNO='1';
SELECT MAX(GRADE) FROM SC WHERE CNO='1';
SELECT SUM(CCREDIT) FROM SC, COURSE WHERE SNO='200215012' AND SC.CNO=COURSE.CNO;
SELECT SUM(CCREDIT) FROM SC, COURSE WHERE SNO='200215121' AND SC.CNO=COURSE.CNO;
*/

-- 3.4.1.5 GROUP BY 子句

/*
SELECT CNO, COUNT(SNO) FROM SC GROUP BY CNO;
SELECT SNO FROM SC GROUP BY SNO HAVING COUNT(*) > 1;
*/


-- 3.4.2.1 等值与非等值连接查询

/*
SELECT STUDENT.*, SC.* FROM STUDENT, SC WHERE STUDENT.SNO=SC.SNO;
SELECT STUDENT.SNO, SNAME, SSEX, SAGE, SDEPT, CNO, GRADE FROM STUDENT, SC WHERE STUDENT.SNO=SC.SNO;
*/

-- 3.4.2.2 自身连接

/*
SELECT FIRST.CNO, SECOND.CPNO FROM COURSE FIRST, COURSE SECOND WHERE FIRST.CPNO=SECOND.CNO;
*/

-- 3.4.2.3 外连接

/*
SELECT STUDENT.SNO, SNAME, SSEX, SAGE, SDEPT, CNO, GRADE FROM STUDENT LEFT JOIN SC ON (STUDENT.SNO=SC.SNO);
SELECT STUDENT.SNO, SNAME, SSEX, SAGE, SDEPT, CNO, GRADE FROM STUDENT RIGHT JOIN SC ON (STUDENT.SNO=SC.SNO);
*/

-- 3.4.2.4 复合条件连接

/*
SELECT STUDENT.SNO, SNAME FROM STUDENT, SC WHERE STUDENT.SNO=SC.SNO AND SC.CNO='2' AND SC.GRADE > 90;
SELECT STUDENT.SNO, SNAME, CNAME, GRADE FROM STUDENT, SC, COURSE WHERE STUDENT.SNO=SC.SNO AND SC.CNO=COURSE.CNO;
*/

-- 3.4.3.1 带有IN谓词的子查询

/*
SELECT SDEPT FROM STUDENT WHERE SNAME='刘晨';
SELECT SNO, SNAME, SDEPT FROM STUDENT WHERE SDEPT='CS';
SELECT SNO, SNAME, SDEPT FROM STUDENT WHERE SDEPT IN (SELECT SDEPT FROM STUDENT WHERE SNAME='刘晨');
SELECT S1.SNO, S1.SNAME, S1.SDEPT FROM STUDENT S1, STUDENT S2 WHERE S1.SDEPT=S2.SDEPT AND S2.SNAME='刘晨';
*/

